ALTER TABLE curso ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE disciplina ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE formulario ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE formulario_versao ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE pergunta_versao ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE opcao_pergunta ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
