-- A V4 preserva OLD_TOKEN e cria NEW_HASH; aqui configuramos a expiração.

ALTER TABLE VALIDACAO ADD COLUMN IF NOT EXISTS EXPIRA_EM timestamp(6);
UPDATE VALIDACAO
SET EXPIRA_EM = coalesce(DATA_CRIACAO, current_timestamp) + interval '14 days'
WHERE EXPIRA_EM IS NULL;
ALTER TABLE VALIDACAO ALTER COLUMN EXPIRA_EM SET NOT NULL;
