-- A identidade técnica desacopla a PK do digest usado como chave de negócio.
ALTER TABLE VALIDACAO
    ADD COLUMN ID BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE VALIDACAO
    DROP CONSTRAINT IF EXISTS VALIDACAO_pkey;

ALTER TABLE VALIDACAO
    ALTER COLUMN ID SET NOT NULL;

ALTER TABLE VALIDACAO
    ADD CONSTRAINT PK_VALIDACAO_ID PRIMARY KEY (ID);

ALTER TABLE VALIDACAO
    ADD CONSTRAINT UK_VALIDACAO_NEW_HASH UNIQUE (NEW_HASH);

-- Rollback operacional: com backup e após confirmar que não existem FKs
-- dependentes, uma migration corretiva pode remover PK_VALIDACAO_ID/ID e
-- restaurar uma chave de negócio como PK. Não editar esta migration após aplicada.
