CREATE TABLE CAMPANHA (
    id BIGSERIAL PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE FORMULARIO (
    id BIGSERIAL PRIMARY KEY,
    codigo VARCHAR(60) NOT NULL,
    nome VARCHAR(180) NOT NULL,
    publico VARCHAR(20) NOT NULL,
    campanha_id BIGINT NOT NULL REFERENCES CAMPANHA(id),
    CONSTRAINT uk_formulario_campanha_codigo UNIQUE (campanha_id, codigo)
);

CREATE TABLE FORMULARIO_VERSAO (
    id BIGSERIAL PRIMARY KEY,
    formulario_id BIGINT NOT NULL REFERENCES FORMULARIO(id),
    numero INTEGER NOT NULL,
    comentario_permitido BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_formulario_versao UNIQUE (formulario_id, numero)
);

CREATE TABLE PERGUNTA_VERSAO (
    id BIGSERIAL PRIMARY KEY,
    formulario_versao_id BIGINT NOT NULL REFERENCES FORMULARIO_VERSAO(id),
    codigo VARCHAR(40) NOT NULL,
    texto VARCHAR(1000) NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT uk_pergunta_versao UNIQUE (formulario_versao_id, codigo)
);

CREATE TABLE OPCAO_PERGUNTA (
    id BIGSERIAL PRIMARY KEY,
    pergunta_versao_id BIGINT NOT NULL REFERENCES PERGUNTA_VERSAO(id),
    codigo VARCHAR(30) NOT NULL,
    rotulo VARCHAR(100) NOT NULL,
    valor INTEGER,
    nao_sei_responder BOOLEAN NOT NULL DEFAULT FALSE,
    ordem INTEGER NOT NULL,
    CONSTRAINT uk_opcao_pergunta UNIQUE (pergunta_versao_id, codigo)
);

ALTER TABLE AVALIACAO ADD COLUMN formulario_versao_id BIGINT REFERENCES FORMULARIO_VERSAO(id);
ALTER TABLE RESPOSTA ADD COLUMN pergunta_versao_id BIGINT REFERENCES PERGUNTA_VERSAO(id);
ALTER TABLE RESPOSTA ADD COLUMN opcao_codigo VARCHAR(30);
ALTER TABLE RESPOSTA ADD COLUMN nao_sei_responder BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE RESPOSTA ALTER COLUMN pergunta_id DROP NOT NULL;
ALTER TABLE RESPOSTA ALTER COLUMN nota DROP NOT NULL;
